package foundation.l3rs1.types;
/** §4.4 Compliance Rule Types */
public enum RuleType {
    TRANSFER_ELIGIBILITY, INVESTOR_CLASSIFICATION, HOLDING_PERIOD,
    GEOGRAPHIC_RESTRICTION, SANCTIONS_SCREENING, TRANSACTION_THRESHOLD,
    AML_TRIGGER, MARKET_RESTRICTION, REDEMPTION_ELIGIBILITY
}
